CREATE OR REPLACE FUNCTION FN_COMPROBAR_CLIENTE(CLIENTE varchar2)
RETURN NUMBER
IS
    VALOR_E NUMBER;
BEGIN
    SELECT COUNT(1) INTO VALOR_E FROM tbl_cliente A WHERE A.dni_cliente = CLIENTE;
    RETURN VALOR_E;
END;

CREATE OR REPLACE FUNCTION FN_COMPROBAR_VENDEDOR(VENDEDOR varchar2)
RETURN NUMBER
IS
    VALOR_E NUMBER;
BEGIN
    SELECT COUNT(1) INTO VALOR_E FROM tbl_vendedor A WHERE A.dni_vendedor = VENDEDOR;
    RETURN VALOR_E;
END;

CREATE OR REPLACE PROCEDURE PD_INGRESAR_VENTA(DATOS_VENTA IN SYS_REFCURSOR, MENSAJE OUT VARCHAR2)
IS
    CURSOR_DATOS SYS_REFCURSOR;
    
    TYPE DATOS_VENTA_C IS RECORD(
        CODIGO_VENTA TBL_VENTA.NRO_VENTA%TYPE,
        FECHA_VENTA TBL_VENTA.FECHA_HORA%TYPE,
        VENDEDOR TBL_VENTA.DNI_VENDEDOR%TYPE,
        CLIENTE TBL_VENTA.DNI_CLIENTE%TYPE,
        TOTAL TBL_VENTA.TOTAL%TYPE,
        CONDICION TBL_VENTA.CONDICION%TYPE
    );
    
    FILA DATOS_VENTA_C;
    
    VALOR_CLI NUMBER;
    VALOR_EMP NUMBER;
BEGIN
    
    FETCH DATOS_VENTA INTO FILA;

    VALOR_CLI := FN_COMPROBAR_CLIENTE(FILA.CLIENTE);
    
    IF VALOR_CLI > 0 THEN
        VALOR_EMP := FN_COMPROBAR_VENDEDOR(FILA.VENDEDOR);
        IF VALOR_EMP > 0 THEN
            INSERT INTO tbl_venta VALUES (FILA.CODIGO_VENTA, FILA.FECHA_VENTA, FILA.VENDEDOR, FILA.CLIENTE, FILA.TOTAL, FILA.CONDICION);
            MENSAJE := 'SE INSERTO CORRECTAMENTE LOS VALORES';
        ELSE
            MENSAJE := 'VALOR DE EMPLEADO NO EXISTE';
        END IF;
    ELSE
        MENSAJE := 'VALOR DE CLIENTE NO EXISTE';
    END IF;
    
    EXCEPTION 
        WHEN OTHERS THEN
            MENSAJE := 'OCURRiO UNA EXCEPCION: ' || SQLCODE;


END;

declare
    datos_ventas sys_refcursor;
    mensaje varchar2(100);
    
begin

    open datos_ventas for select 1 id, systimestamp fecha, 'GBJ7AB' ven, 'B0K7U2' cli, 100.20 total, 'Deudor' condi from dual;

    PD_INGRESAR_VENTA(datos_ventas, mensaje);
    
    dbms_output.put_line(mensaje);
    
    close datos_ventas;
end;

